package com.ventoydroid.app.fat

/**
 * The canonical exFAT up-case table (Unicode simple upper-casing), byte-identical to
 * the table written by mkfs.exfat and the Windows formatter (5836 bytes = 2918 UTF-16
 * code units). Extracted from exfatprogs 1.2.2 mkfs/upcase.c; its well-known checksum
 * is 0xE619D30D, which is what goes into the up-case root directory entry.
 * SPDX-License-Identifier: GPL-2.0-or-later (table data)
 */
internal object ExFatUpcase {
    const val TABLE_BYTES = 5836
    const val TABLE_CHECKSUM = 0xE619D30DL
    const val ENTRY_COUNT = 2918

    private const val BASE64 =
        "AAABAAIAAwAEAAUABgAHAAgACQAKAAsADAANAA4ADwAQABEAEgATABQAFQAWABcAGAAZABoAGwAcAB0AHgAfACAAIQAiACMAJAAlACYAJwAoACkAKgAr" +
        "ACwALQAuAC8AMAAxADIAMwA0ADUANgA3ADgAOQA6ADsAPAA9AD4APwBAAEEAQgBDAEQARQBGAEcASABJAEoASwBMAE0ATgBPAFAAUQBSAFMAVABVAFYA" +
        "VwBYAFkAWgBbAFwAXQBeAF8AYABBAEIAQwBEAEUARgBHAEgASQBKAEsATABNAE4ATwBQAFEAUgBTAFQAVQBWAFcAWABZAFoAewB8AH0AfgB/AIAAgQCC" +
        "AIMAhACFAIYAhwCIAIkAigCLAIwAjQCOAI8AkACRAJIAkwCUAJUAlgCXAJgAmQCaAJsAnACdAJ4AnwCgAKEAogCjAKQApQCmAKcAqACpAKoAqwCsAK0A" +
        "rgCvALAAsQCyALMAtAC1ALYAtwC4ALkAugC7ALwAvQC+AL8AwADBAMIAwwDEAMUAxgDHAMgAyQDKAMsAzADNAM4AzwDQANEA0gDTANQA1QDWANcA2ADZ" +
        "ANoA2wDcAN0A3gDfAMAAwQDCAMMAxADFAMYAxwDIAMkAygDLAMwAzQDOAM8A0ADRANIA0wDUANUA1gD3ANgA2QDaANsA3ADdAN4AeAEAAQABAgECAQQB" +
        "BAEGAQYBCAEIAQoBCgEMAQwBDgEOARABEAESARIBFAEUARYBFgEYARgBGgEaARwBHAEeAR4BIAEgASIBIgEkASQBJgEmASgBKAEqASoBLAEsAS4BLgEw" +
        "ATEBMgEyATQBNAE2ATYBOAE5ATkBOwE7AT0BPQE/AT8BQQFBAUMBQwFFAUUBRwFHAUkBSgFKAUwBTAFOAU4BUAFQAVIBUgFUAVQBVgFWAVgBWAFaAVoB" +
        "XAFcAV4BXgFgAWABYgFiAWQBZAFmAWYBaAFoAWoBagFsAWwBbgFuAXABcAFyAXIBdAF0AXYBdgF4AXkBeQF7AXsBfQF9AX8BQwKBAYIBggGEAYQBhgGH" +
        "AYcBiQGKAYsBiwGNAY4BjwGQAZEBkQGTAZQB9gGWAZcBmAGYAT0CmwGcAZ0BIAKfAaABoAGiAaIBpAGkAaYBpwGnAakBqgGrAawBrAGuAa8BrwGxAbIB" +
        "swGzAbUBtQG3AbgBuAG6AbsBvAG8Ab4B9wHAAcEBwgHDAcQBxQHEAccByAHHAcoBywHKAc0BzQHPAc8B0QHRAdMB0wHVAdUB1wHXAdkB2QHbAdsBjgHe" +
        "Ad4B4AHgAeIB4gHkAeQB5gHmAegB6AHqAeoB7AHsAe4B7gHwAfEB8gHxAfQB9AH2AfcB+AH4AfoB+gH8AfwB/gH+AQACAAICAgICBAIEAgYCBgIIAggC" +
        "CgIKAgwCDAIOAg4CEAIQAhICEgIUAhQCFgIWAhgCGAIaAhoCHAIcAh4CHgIgAiECIgIiAiQCJAImAiYCKAIoAioCKgIsAiwCLgIuAjACMAIyAjICNAI1" +
        "AjYCNwI4AjkCZSw7AjsCPQJmLD8CQAJBAkECQwJEAkUCRgJGAkgCSAJKAkoCTAJMAk4CTgJQAlECUgKBAYYBVQKJAYoBWAKPAVoCkAFcAl0CXgJfApMB" +
        "YQJiApQBZAJlAmYCZwKXAZYBagJiLGwCbQJuApwBcAJxAp0BcwJ0Ap8BdgJ3AngCeQJ6AnsCfAJkLH4CfwKmAYECggKpAYQChQKGAocCrgFEArEBsgFF" +
        "Ao0CjgKPApACkQK3AZMClAKVApYClwKYApkCmgKbApwCnQKeAp8CoAKhAqICowKkAqUCpgKnAqgCqQKqAqsCrAKtAq4CrwKwArECsgKzArQCtQK2ArcC" +
        "uAK5AroCuwK8Ar0CvgK/AsACwQLCAsMCxALFAsYCxwLIAskCygLLAswCzQLOAs8C0ALRAtIC0wLUAtUC1gLXAtgC2QLaAtsC3ALdAt4C3wLgAuEC4gLj" +
        "AuQC5QLmAucC6ALpAuoC6wLsAu0C7gLvAvAC8QLyAvMC9AL1AvYC9wL4AvkC+gL7AvwC/QL+Av8CAAMBAwIDAwMEAwUDBgMHAwgDCQMKAwsDDAMNAw4D" +
        "DwMQAxEDEgMTAxQDFQMWAxcDGAMZAxoDGwMcAx0DHgMfAyADIQMiAyMDJAMlAyYDJwMoAykDKgMrAywDLQMuAy8DMAMxAzIDMwM0AzUDNgM3AzgDOQM6" +
        "AzsDPAM9Az4DPwNAA0EDQgNDA0QDRQNGA0cDSANJA0oDSwNMA00DTgNPA1ADUQNSA1MDVANVA1YDVwNYA1kDWgNbA1wDXQNeA18DYANhA2IDYwNkA2UD" +
        "ZgNnA2gDaQNqA2sDbANtA24DbwNwA3EDcgNzA3QDdQN2A3cDeAN5A3oD/QP+A/8DfgN/A4ADgQOCA4MDhAOFA4YDhwOIA4kDigOLA4wDjQOOA48DkAOR" +
        "A5IDkwOUA5UDlgOXA5gDmQOaA5sDnAOdA54DnwOgA6EDogOjA6QDpQOmA6cDqAOpA6oDqwOGA4gDiQOKA7ADkQOSA5MDlAOVA5YDlwOYA5kDmgObA5wD" +
        "nQOeA58DoAOhA6MDowOkA6UDpgOnA6gDqQOqA6sDjAOOA48DzwPQA9ED0gPTA9QD1QPWA9cD2APYA9oD2gPcA9wD3gPeA+AD4APiA+ID5APkA+YD5gPo" +
        "A+gD6gPqA+wD7APuA+4D8APxA/kD8wP0A/UD9gP3A/cD+QP6A/oD/AP9A/4D/wMABAEEAgQDBAQEBQQGBAcECAQJBAoECwQMBA0EDgQPBBAEEQQSBBME" +
        "FAQVBBYEFwQYBBkEGgQbBBwEHQQeBB8EIAQhBCIEIwQkBCUEJgQnBCgEKQQqBCsELAQtBC4ELwQQBBEEEgQTBBQEFQQWBBcEGAQZBBoEGwQcBB0EHgQf" +
        "BCAEIQQiBCMEJAQlBCYEJwQoBCkEKgQrBCwELQQuBC8EAAQBBAIEAwQEBAUEBgQHBAgECQQKBAsEDAQNBA4EDwRgBGAEYgRiBGQEZARmBGYEaARoBGoE" +
        "agRsBGwEbgRuBHAEcARyBHIEdAR0BHYEdgR4BHgEegR6BHwEfAR+BH4EgASABIIEgwSEBIUEhgSHBIgEiQSKBIoEjASMBI4EjgSQBJAEkgSSBJQElASW" +
        "BJYEmASYBJoEmgScBJwEngSeBKAEoASiBKIEpASkBKYEpgSoBKgEqgSqBKwErASuBK4EsASwBLIEsgS0BLQEtgS2BLgEuAS6BLoEvAS8BL4EvgTABMEE" +
        "wQTDBMMExQTFBMcExwTJBMkEywTLBM0EzQTABNAE0ATSBNIE1ATUBNYE1gTYBNgE2gTaBNwE3ATeBN4E4ATgBOIE4gTkBOQE5gTmBOgE6ATqBOoE7ATs" +
        "BO4E7gTwBPAE8gTyBPQE9AT2BPYE+AT4BPoE+gT8BPwE/gT+BAAFAAUCBQIFBAUEBQYFBgUIBQgFCgUKBQwFDAUOBQ4FEAUQBRIFEgUUBRUFFgUXBRgF" +
        "GQUaBRsFHAUdBR4FHwUgBSEFIgUjBSQFJQUmBScFKAUpBSoFKwUsBS0FLgUvBTAFMQUyBTMFNAU1BTYFNwU4BTkFOgU7BTwFPQU+BT8FQAVBBUIFQwVE" +
        "BUUFRgVHBUgFSQVKBUsFTAVNBU4FTwVQBVEFUgVTBVQFVQVWBVcFWAVZBVoFWwVcBV0FXgVfBWAFMQUyBTMFNAU1BTYFNwU4BTkFOgU7BTwFPQU+BT8F" +
        "QAVBBUIFQwVEBUUFRgVHBUgFSQVKBUsFTAVNBU4FTwVQBVEFUgVTBVQFVQVWBf//9hdjLH4dfx2AHYEdgh2DHYQdhR2GHYcdiB2JHYodix2MHY0djh2P" +
        "HZAdkR2SHZMdlB2VHZYdlx2YHZkdmh2bHZwdnR2eHZ8doB2hHaIdox2kHaUdph2nHagdqR2qHasdrB2tHa4drx2wHbEdsh2zHbQdtR22HbcduB25Hbod" +
        "ux28Hb0dvh2/HcAdwR3CHcMdxB3FHcYdxx3IHckdyh3LHcwdzR3OHc8d0B3RHdId0x3UHdUd1h3XHdgd2R3aHdsd3B3dHd4d3x3gHeEd4h3jHeQd5R3m" +
        "Hecd6B3pHeod6x3sHe0d7h3vHfAd8R3yHfMd9B31HfYd9x34Hfkd+h37Hfwd/R3+Hf8dAB4AHgIeAh4EHgQeBh4GHggeCB4KHgoeDB4MHg4eDh4QHhAe" +
        "Eh4SHhQeFB4WHhYeGB4YHhoeGh4cHhweHh4eHiAeIB4iHiIeJB4kHiYeJh4oHigeKh4qHiweLB4uHi4eMB4wHjIeMh40HjQeNh42HjgeOB46HjoePB48" +
        "Hj4ePh5AHkAeQh5CHkQeRB5GHkYeSB5IHkoeSh5MHkweTh5OHlAeUB5SHlIeVB5UHlYeVh5YHlgeWh5aHlweXB5eHl4eYB5gHmIeYh5kHmQeZh5mHmge" +
        "aB5qHmoebB5sHm4ebh5wHnAech5yHnQedB52HnYeeB54Hnoeeh58Hnwefh5+HoAegB6CHoIehB6EHoYehh6IHogeih6KHowejB6OHo4ekB6QHpIekh6U" +
        "HpQelh6XHpgemR6aHpsenB6dHp4enx6gHqAeoh6iHqQepB6mHqYeqB6oHqoeqh6sHqwerh6uHrAesB6yHrIetB60HrYeth64Hrgeuh66HrwevB6+Hr4e" +
        "wB7AHsIewh7EHsQexh7GHsgeyB7KHsoezB7MHs4ezh7QHtAe0h7SHtQe1B7WHtYe2B7YHtoe2h7cHtwe3h7eHuAe4B7iHuIe5B7kHuYe5h7oHuge6h7q" +
        "Huwe7B7uHu4e8B7wHvIe8h70HvQe9h72Hvge+B76Hvse/B79Hv4e/x4IHwkfCh8LHwwfDR8OHw8fCB8JHwofCx8MHw0fDh8PHxgfGR8aHxsfHB8dHxYf" +
        "Fx8YHxkfGh8bHxwfHR8eHx8fKB8pHyofKx8sHy0fLh8vHygfKR8qHysfLB8tHy4fLx84HzkfOh87HzwfPR8+Hz8fOB85HzofOx88Hz0fPh8/H0gfSR9K" +
        "H0sfTB9NH0YfRx9IH0kfSh9LH0wfTR9OH08fUB9ZH1IfWx9UH10fVh9fH1gfWR9aH1sfXB9dH14fXx9oH2kfah9rH2wfbR9uH28faB9pH2ofax9sH20f" +
        "bh9vH7ofux/IH8kfyh/LH9of2x/4H/kf6h/rH/of+x9+H38fiB+JH4ofix+MH40fjh+PH4gfiR+KH4sfjB+NH44fjx+YH5kfmh+bH5wfnR+eH58fmB+Z" +
        "H5ofmx+cH50fnh+fH6gfqR+qH6sfrB+tH64frx+oH6kfqh+rH6wfrR+uH68fuB+5H7IfvB+0H7Ufth+3H7gfuR+6H7sfvB+9H74fvx/AH8Efwh/DH8Qf" +
        "xR/GH8cfyB/JH8ofyx/DH80fzh/PH9gf2R/SH9Mf1B/VH9Yf1x/YH9kf2h/bH9wf3R/eH98f6B/pH+If4x/kH+wf5h/nH+gf6R/qH+sf7B/tH+4f7x/w" +
        "H/Ef8h/zH/Qf9R/2H/cf+B/5H/of+x/zH/0f/h//HwAgASACIAMgBCAFIAYgByAIIAkgCiALIAwgDSAOIA8gECARIBIgEyAUIBUgFiAXIBggGSAaIBsg" +
        "HCAdIB4gHyAgICEgIiAjICQgJSAmICcgKCApICogKyAsIC0gLiAvIDAgMSAyIDMgNCA1IDYgNyA4IDkgOiA7IDwgPSA+ID8gQCBBIEIgQyBEIEUgRiBH" +
        "IEggSSBKIEsgTCBNIE4gTyBQIFEgUiBTIFQgVSBWIFcgWCBZIFogWyBcIF0gXiBfIGAgYSBiIGMgZCBlIGYgZyBoIGkgaiBrIGwgbSBuIG8gcCBxIHIg" +
        "cyB0IHUgdiB3IHggeSB6IHsgfCB9IH4gfyCAIIEggiCDIIQghSCGIIcgiCCJIIogiyCMII0gjiCPIJAgkSCSIJMglCCVIJYglyCYIJkgmiCbIJwgnSCe" +
        "IJ8goCChIKIgoyCkIKUgpiCnIKggqSCqIKsgrCCtIK4gryCwILEgsiCzILQgtSC2ILcguCC5ILoguyC8IL0gviC/IMAgwSDCIMMgxCDFIMYgxyDIIMkg" +
        "yiDLIMwgzSDOIM8g0CDRINIg0yDUINUg1iDXINgg2SDaINsg3CDdIN4g3yDgIOEg4iDjIOQg5SDmIOcg6CDpIOog6yDsIO0g7iDvIPAg8SDyIPMg9CD1" +
        "IPYg9yD4IPkg+iD7IPwg/SD+IP8gACEBIQIhAyEEIQUhBiEHIQghCSEKIQshDCENIQ4hDyEQIREhEiETIRQhFSEWIRchGCEZIRohGyEcIR0hHiEfISAh" +
        "ISEiISMhJCElISYhJyEoISkhKiErISwhLSEuIS8hMCExITIhMyE0ITUhNiE3ITghOSE6ITshPCE9IT4hPyFAIUEhQiFDIUQhRSFGIUchSCFJIUohSyFM" +
        "IU0hMiFPIVAhUSFSIVMhVCFVIVYhVyFYIVkhWiFbIVwhXSFeIV8hYCFhIWIhYyFkIWUhZiFnIWghaSFqIWshbCFtIW4hbyFgIWEhYiFjIWQhZSFmIWch" +
        "aCFpIWohayFsIW0hbiFvIYAhgSGCIYMhgyH//0sDtiS3JLgkuSS6JLskvCS9JL4kvyTAJMEkwiTDJMQkxSTGJMckyCTJJMokyyTMJM0kziTPJP//RgcA" +
        "LAEsAiwDLAQsBSwGLAcsCCwJLAosCywMLA0sDiwPLBAsESwSLBMsFCwVLBYsFywYLBksGiwbLBwsHSweLB8sICwhLCIsIywkLCUsJiwnLCgsKSwqLCss" +
        "LCwtLC4sXyxgLGAsYixjLGQsZSxmLGcsZyxpLGksayxrLG0sbixvLHAscSxyLHMsdCx1LHUsdyx4LHkseix7LHwsfSx+LH8sgCyALIIsgiyELIQshiyG" +
        "LIgsiCyKLIosjCyMLI4sjiyQLJAskiySLJQslCyWLJYsmCyYLJosmiycLJwsniyeLKAsoCyiLKIspCykLKYspiyoLKgsqiyqLKwsrCyuLK4ssCywLLIs" +
        "siy0LLQstiy2LLgsuCy6LLosvCy8LL4svizALMAswizCLMQsxCzGLMYsyCzILMosyizMLMwszizOLNAs0CzSLNIs1CzULNYs1izYLNgs2izaLNws3Cze" +
        "LN4s4CzgLOIs4izkLOUs5iznLOgs6SzqLOss7CztLO4s7yzwLPEs8izzLPQs9Sz2LPcs+Cz5LPos+yz8LP0s/iz/LKAQoRCiEKMQpBClEKYQpxCoEKkQ" +
        "qhCrEKwQrRCuEK8QsBCxELIQsxC0ELUQthC3ELgQuRC6ELsQvBC9EL4QvxDAEMEQwhDDEMQQxRD//xvSIf8i/yP/JP8l/yb/J/8o/yn/Kv8r/yz/Lf8u" +
        "/y//MP8x/zL/M/80/zX/Nv83/zj/Of86/1v/XP9d/17/X/9g/2H/Yv9j/2T/Zf9m/2f/aP9p/2r/a/9s/23/bv9v/3D/cf9y/3P/dP91/3b/d/94/3n/" +
        "ev97/3z/ff9+/3//gP+B/4L/g/+E/4X/hv+H/4j/if+K/4v/jP+N/47/j/+Q/5H/kv+T/5T/lf+W/5f/mP+Z/5r/m/+c/53/nv+f/6D/of+i/6P/pP+l" +
        "/6b/p/+o/6n/qv+r/6z/rf+u/6//sP+x/7L/s/+0/7X/tv+3/7j/uf+6/7v/vP+9/77/v//A/8H/wv/D/8T/xf/G/8f/yP/J/8r/y//M/83/zv/P/9D/" +
        "0f/S/9P/1P/V/9b/1//Y/9n/2v/b/9z/3f/e/9//4P/h/+L/4//k/+X/5v/n/+j/6f/q/+v/7P/t/+7/7//w//H/8v/z//T/9f/2//f/+P/5//r/+//8" +
        "//3//v///w=="

    /** Decodes the table into UTF-16 code units indexed by code point. */
    fun decoded(): ShortArray {
        val bytes = decodedBytes()
        val out = ShortArray(ENTRY_COUNT)
        for (i in 0 until ENTRY_COUNT) {
            val lo = bytes[i * 2].toInt() and 0xFF
            val hi = bytes[i * 2 + 1].toInt() and 0xFF
            out[i] = ((hi shl 8) or lo).toShort()
        }
        return out
    }

    /** Decodes the raw table bytes as written to disk (little-endian UTF-16). */
    fun decodedBytes(): ByteArray {
        val bytes = java.util.Base64.getDecoder().decode(BASE64)
        check(bytes.size == TABLE_BYTES)
        return bytes
    }
}
